# CASE STATUS
# CASE LISTING DETAILS (Tentative)
# PETITIONER/APPLICANT DETAIL
# RESPONDENTS/DEFENDENT DETAILS
# PROPERTY DETAILS
# CASE PROCEEDING DETAILS
# RC/TRC CASE CURRENT STATUS
# RC CASE PROCEEDING DETAILS

import simplematch
from bs4 import BeautifulSoup
import re
from unicodedata import normalize

